final Map<String, String> bnUS = {
  'appTitle': 'সাবস্ক্রিপশন ম্যানেজার',
  'dashboard': 'ড্যাশবোর্ড',
  'general': 'সাধারণ',
  'subscriptions': 'সাবস্ক্রিপশন',
  'settings': 'সেটিংস',
  'upcoming': 'আসন্ন',
  'items': 'টি',
  'cost': 'মূল্য',
  'edit': 'সম্পাদনা',
  'delete': 'মুছে ফেলুন',
  'currency': 'মুদ্রা',
  'language': 'ভাষা',
  'theme': 'থিম',
  'payment_reminder': 'পেমেন্ট রিমাইন্ডার',
  'reminder_cadence': 'রিমাইন্ডার কেডেন্স',
  'reminder_time': 'রিমাইন্ডার সময়',
  'subscription_dashboard': 'সাবস্ক্রিপশন ড্যাশবোর্ড',
  'notifications': 'নোটিফিকেশন',
  'support': 'সাপোর্ট',
  'about': 'সম্পর্কে',
  'more_info': 'আরও তথ্য',
  'contact_support': 'সাপোর্টে যোগাযোগ',
  'rate_us': 'রেট করুন',
  'privacy_policy': 'গোপনীয়তা নীতি',
  'terms_and_conditions': 'শর্তাবলী',
  'version': 'ভার্সন',
  'more_apps': 'আরও অ্যাপ',
  'choose_currency': 'মুদ্রা নির্বাচন করুন',
  'choose_language': 'ভাষা নির্বাচন করুন',
  'choose_theme': 'থিম নির্বাচন করুন',
  'reminder_schedule': 'রিমাইন্ডার সময়সূচি',
  'selected_time_for_the_reminder': 'রিমাইন্ডারের জন্য নির্বাচিত সময়',
  'enable_payment_reminder_to_change_time': 'সময় পরিবর্তন করতে পেমেন্ট রিমাইন্ডার চালু করুন',
  'send_app_version_device_and_os_details': 'অ্যাপ, ভার্সন, ডিভাইস এবং OS বিস্তারিত পাঠান',
  'tell_us_how_the_app_feels': 'অ্যাপটি কেমন লাগে জানান',
  'create_subscription': 'সাবস্ক্রিপশন তৈরি করুন',
  'subscription_name': 'সাবস্ক্রিপশনের নাম',
  'payment_cycle': 'পেমেন্ট সাইকেল',
  'start_date': 'শুরুর তারিখ',
  'payment_method': 'পেমেন্ট পদ্ধতি',
  'note': 'নোট',
  'note_optional': 'নোট (ঐচ্ছিক)',
  'renewal': 'নবায়ন',
  'netflix_premium': 'নেটফ্লিক্স প্রিমিয়াম',
  'add_any_note': 'যেকোনো নোট যোগ করুন...',
  'yearly_spend': 'বার্ষিক খরচ',
  'monthly_spend': 'মাসিক খরচ',
  'saved_subscriptions_count': '@count টি সংরক্ষিত সাবস্ক্রিপশন',
  'upcoming_items': '@count টি',
  'subscription_plan': '@cycle প্ল্যান',
  'save': 'সেভ',
  'no_saved_subscriptions_yet_create_one_to_see_it_here': 'এখনও কোনো সাবস্ক্রিপশন নেই। দেখতে একটি তৈরি করুন।',
  'subscription_not_found': 'সাবস্ক্রিপশন পাওয়া যায়নি',
  'it_may_have_been_deleted_already': 'এটি সম্ভবত মুছে ফেলা হয়েছে।',
  'back': 'ফিরে যান',
  'subscription_details': 'সাবস্ক্রিপশনের বিস্তারিত',
  'delete_subscription': 'সাবস্ক্রিপশন মুছবেন?',
  'this_action_cannot_be_undone': 'এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',
  'cancel': 'বাতিল',
  'update': 'আপডেট',
  'expired': 'মেয়াদ শেষ',
  'day_left': '১ দিন বাকি',
  'days_left': '@days দিন বাকি',
  'selected_currency_display': '@name (@symbol)',
};