final Map<String, String> enUS = {
  'appTitle': 'Subscription Manager',
  'dashboard': 'Dashboard',
  'general': 'General',
  'subscriptions': 'Subscriptions',
  'settings': 'Settings',
  'upcoming': 'Upcoming',
  'items': 'items',
  'cost': 'Cost',
  'edit': 'Edit',
  'delete': 'Delete',
  'currency': 'Currency',
  'language': 'Language',
  'theme': 'Theme',
  'payment_reminder': 'Payment Reminder',
  'reminder_cadence': 'Reminder Cadence',
  'reminder_time': 'Reminder Time',
  'subscription_dashboard': 'Subscription Dashboard',
  'notifications': 'Notifications',
  'support': 'Support',
  'about': 'About',
  'more_info': 'More Info',
  'contact_support': 'Contact Support',
  'rate_us': 'Rate Us',
  'privacy_policy': 'Privacy Policy',
  'terms_and_conditions': 'Terms and Conditions',
  'version': 'Version',
  'more_apps': 'More Apps',
  'choose_currency': 'Choose currency',
  'choose_language': 'Choose language',
  'choose_theme': 'Choose theme',
  'reminder_schedule': 'Reminder schedule',
  'selected_time_for_the_reminder': 'Selected time for the reminder',
  'enable_payment_reminder_to_change_time': 'Enable payment reminder to change time',
  'send_app_version_device_and_os_details': 'Send app, version, device, and OS details',
  'tell_us_how_the_app_feels': 'Tell us how the app feels',
  'create_subscription': 'Create Subscription',
  'subscription_name': 'Subscription name',
  'payment_cycle': 'Payment cycle',
  'start_date': 'Start Date',
  'payment_method': 'Payment Method',
  'note': 'Note',
  'note_optional': 'Note (Optional)',
  'renewal': 'Renewal',
  'netflix_premium': 'Netflix Premium',
  'add_any_note': 'Add any note...',
  'yearly_spend': 'Yearly Spend',
  'monthly_spend': 'Monthly Spend',
  'saved_subscriptions_count': '@count Saved subscriptions',
  'upcoming_items': '@count items',
  'subscription_plan': '@cycle plan',
  'save': 'SAVE',
  'no_saved_subscriptions_yet_create_one_to_see_it_here': 'No saved subscriptions yet. Create one to see it here.',
  'subscription_not_found': 'Subscription not found',
  'it_may_have_been_deleted_already': 'It may have been deleted already.',
  'back': 'Back',
  'subscription_details': 'Subscription Details',
  'delete_subscription': 'Delete subscription?',
  'this_action_cannot_be_undone': 'This action cannot be undone.',
  'cancel': 'Cancel',
  'update': 'Update',
  'expired': 'Expired',
  'day_left': '1 day left',
  'days_left': '@days days left',
  'selected_currency_display': '@name (@symbol)',
};